runtime: python39
entrypoint: gunicorn -b :$PORT main:app

instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.6
  min_instances: 1
  max_instances: 1
  min_idle_instances: 0
  max_idle_instances: 0